{"name": "test_login_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <testbag.test_feature_story.Testlogin object at 0x000002414DFF5278>\n\n    @allure.story(\"密码缺失\")#子功能名称\n    def test_login_failure(self):\n        with allure.step(\"点击用户名\"):  #标注测试步骤\n            print(\"输入用户名\")\n        with allure.step(\"点击密码\"):\n            print(\"输入密码\")\n        print(\"点击登录\")\n        with allure.step(\"点击登录之后登录失败\"):\n>           assert '1'== 1\nE           AssertionError: assert '1' == 1\n\ntest_feature_story.py:26: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1637927535177, "stop": 1637927535177}, {"name": "点击密码", "status": "passed", "start": 1637927535178, "stop": 1637927535178}, {"name": "点击登录之后登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"G:\\Workspace\\pyworkspace\\testbag\\test_feature_story.py\", line 26, in test_login_failure\n    assert '1'== 1\n"}, "start": 1637927535178, "stop": 1637927535178}], "attachments": [{"name": "stdout", "source": "f8b578a5-115d-4413-837c-9a2d5fdb99ef-attachment.txt", "type": "text/plain"}], "start": 1637927535177, "stop": 1637927535178, "uuid": "b0c7f365-c189-4ed2-a2ec-c058f9fd5d15", "historyId": "5752c6907a958d7aa13999772e83267c", "testCaseId": "9bc626654adbb3984c32933a66d9b511", "fullName": "test_feature_story.Testlogin#test_login_failure", "labels": [{"name": "feature", "value": "登录"}, {"name": "story", "value": "密码缺失"}, {"name": "suite", "value": "test_feature_story"}, {"name": "subSuite", "value": "Testlogin"}, {"name": "host", "value": "LAPTOP-QMS0DV6U"}, {"name": "thread", "value": "24304-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_feature_story"}]}