{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test failure\"\"\"\n>       assert False\nE       assert False\n\ntest_alluredemo.py:7: AssertionError"}, "description": "this test failure", "start": 1637912136791, "stop": 1637912136791, "uuid": "914a035f-0007-45bf-a432-acef47255fd0", "historyId": "e3535563f27e644c4a3371e45c952575", "testCaseId": "cdaed0cfb7279459338013af0d443b47", "fullName": "test_alluredemo#test_failure", "labels": [{"name": "suite", "value": "test_alluredemo"}, {"name": "host", "value": "LAPTOP-QMS0DV6U"}, {"name": "thread", "value": "21592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_alluredemo"}]}